--- 
- name: Morpheus UI | Push Morpheus config
  template:
    src: morph.config.j2
    dest: /etc/morpheus/morpheus.rb
  register: configpush

- name: Push trusted CA files
  copy:
    src: "{{ item }}"
    dest: "/etc/morpheus/ssl/trusted_certs/{{ item }}"
  when: morpheus_trusted_ca_files

#  - name: Register CA in keystore
#    command: "/opt/morpheus/embedded/java/bin/keytool -import -keystore /opt/morpheus/embedded/java/lib/security/cacerts --trustcacerts -file /tmp/{{ rabbitmq_tls_custom_cabundle_filename }} -storepass changeit -noprompt"
#    register: ca_output
#    retries: 2
#    until: "'Certificate was added to keystore' in ca_output.stderr or 'already exists' in ca_output.stdout"
#    failed_when: ca_output.rc != 0 and ca_output.rc != 1
#    changed_when: "'Certificate was added to keystore' in ca_output.stderr"
#  when: morpheus_rabbitmq_use_tls

- name: Reconfigure hosts
  include_tasks: morpheus_run_reconfigure.yml
  when: ( morpheus_upgrade_flag == false )

- name: Upgrade Morpheus
  include_tasks: morpheus_upgrade.yml
  when: ( morpheus_upgrade_flag == true )