- name: Get Secrets
  slurp:
    src: /etc/morpheus/morpheus-secrets.json
  register: secretsjson

- name: Set secrets var
  set_fact:
    morpheussec: "{{ secretsjson['content'] | b64decode }}"

- name: Set Rabbit morphpass
  set_fact:
    rabbit_morphpass: "{{ morpheussec['rabbitmq']['morpheus_password'] }}"
  delegate_to: "{{ groups[morpheus_group][0] }}"
  run_once: true

- name: Set Rabbit queuepass
  set_fact:
    rabbit_queuepass: "{{ morpheussec['rabbitmq']['queue_user_password'] }}"
  delegate_to: "{{ groups[morpheus_group][0] }}"
  run_once: true

- name: Set Rabbit cookie config
  set_fact:
    rabbit_cookie: "{{ morpheussec['rabbitmq']['cookie'] }}"
  delegate_to: "{{ groups[morpheus_group][0] }}"
  run_once: true

- name: Set rabbitmq secret on other nodes from master
  template:
    src: ../templates/morpheus-secrets.json.j2
    dest: /etc/morpheus/morpheus-secrets.json

- name: Set erlang cookie
  template:
    src: ../templates/erlang.cookie.j2
    dest: /opt/morpheus/embedded/rabbitmq/.erlang.cookie

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups[morpheus_group] }}"

