--- 
- name: Morpheus UI | Push Morpheus config
  template:
    src: morph.config.j2
    dest: /etc/morpheus/morpheus.rb
  register: configpush

- name: Reconfigure hosts
  include_tasks: morpheus_run_reconfigure.yml
  when: ( morpheus_upgrade_flag == false )

- name: Upgrade Morpheus
  include_tasks: morpheus_upgrade.yml
  when: ( morpheus_upgrade_flag == true )